version: "3"
services:
  server:
    build:
      context: etc/docker
      dockerfile: ./server/Dockerfile
    volumes:
      - ./etc/server:/docker/etc
      - ./:/app/local
      - /home/me
    ports:
      - 8080:8080
      - 8081:8081
