version: "3"
services:
  server:
    build:
      context: etc/docker
      dockerfile: ./server/Dockerfile
    volumes:
      - ./etc/server:/docker/etc
      - ./:/app/local
      - /home/me

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400