version: "3"
services:
  server:
    build:
      context: etc/docker
      dockerfile: ./server/Dockerfile
    volumes:
      - home:/home/me
      - app:/app
      - ./etc/server:/docker/etc
      - ./:/app/local
volumes:
  home:
  app:
  
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400